### ISSUE TITLE
Modal on mobile

### ISSUE THREAD

**Issue by rvt** [ggedde/spry-css#1]
hello,

the large modal is not scrollable on a mobile screen so that the close button is not visible. What would be the recommended way to solve this?

**Comment by ggedde** [comment]
Hi @rvt,
In the current docs you can see where it is using `mh-500` as an example to set the max height on the div that contains your content.

You can also apply something like `vh-50` which will set the viewport height to 50%. You can also use both together. You might need to test this on your application, but you can use any percentage with `vh-xx`. This doesn't account for a header or footer with your modal so you will have to adjust accordingly.

Let me know how that goes?

**Comment by rvt** [comment]
Hey @ggedde I have actually decided not to us the modal for the larger forms but I will redirect to a new 'page'. And I think this will work well in my cause. The modal's I will then keep for the 'are you sure' type of messages...

Side Note: I am using spry-css with frameable/el because we this needs to run from a microcontroller, I am down to 20K zipped for the complete system so that's nice :)

**Comment by ggedde** [comment]
Hi @rvt,
That sounds good. I am glad SpryCss is working out for you and hope it works well for the rest of your project.
I am currently working on Version 3 and will be updating the cards within the modals to have a max viewport height so they should never extend out of the view. It might be awhile before V3 is out as it still needs some work and has a bit larger bundle size, but I am working on bringing it back down.

**Comment by ggedde** [comment]
Closing as issue has a work-around and will be updated in Version 3.
